### ISSUE TITLE
getRandomText(minLength, maxLength) doesn't produce real words when minLength too large

### ISSUE THREAD

**Issue by meyertee** [andygibson/datafactory#8]
`dataFactory.getRandomText(20, 40)` for example only generates strings with random characters. The reason seems to be that the method passes the length of the whole text to the `getRandomWord(length)` method, which doesn't find a single word for that length.

**Comment by meyertee** [comment]
Seems to be an easy fix, just created a pull request for it.

**Comment by xenoterracide** [comment]
any chance a release will happen soon?

**Comment by y4nnick** [comment]
I would also need this fix!
